version: 3.9

services:
  application:
    build:
      context: ./application/RFGram
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 RFGram:app
    ports:
     - 5000:5000

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - application