version: "3.9"

services:
  application:
    build:
      context: ./application/RFGram
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 RFGram:app
    volumes:
      - static_media:/home/app/application/application/static/media
      - static_profile_pics:/home/app/application/application/static/profile_pics
    env_file:
      - ./services/env/app.env
    expose:
      - 5000
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    volumes:
      - static_media:/home/app/application/application/static/media
      - static_profile_pics:/home/app/application/application/static/profile_pics
    ports:
      - 80:80
    depends_on:
      - application
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/env/postgres.env
    expose:
      - 5432
    restart: unless-stopped


  dbeaver:
    image: dbeaver/cloudbeaver:latest
    env_file:
      - ./services/env/dbeaver.env
    volumes:
       - dbeaver_workspace:/opt/cloudbeaver/workspace
    ports:
      - 9000:8978
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres_data:
  dbeaver_workspace:
  static_media:
  static_profile_pics: