version: 3.9

services:
  application:
    build:
      context: ./application/RFGram
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 RFGram:app
    env_file:
      - ./services/env/app.env
    expose:
      - 5000
    depends_on:
      - postgres

  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - application

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/env/postgres.env
    expose:
      - 5432

volumes:
  postgres_data: